services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - "${WEB_PORT}:5173"

    environment:
      VITE_API_URL: http://localhost:${API_PORT}

  api:
    depends_on:
      - db

    build: ./backend
    ports:
      - "${API_PORT}:8000"

    environment:
      DB_URL: mongodb://db/anime

  db:
    image: mongo:latest
    ports:
      - "${DB_PORT}:27017"

    volumes:
      - db_volume:/data/db

volumes:
  db_volume:
